### ISSUE TITLE
Exception:  Unable to partition rows

### ISSUE THREAD

**Issue by kartzke** [adamlatchem/toolchest#8]
Hey Adam, nice work on this project!  I've been trying to use it to pull large volume of GSC data.  I ran into an issue where there was more than 25000 rows in the response, so I updated the `execute_request` function to handle pagination.  I followed the flows in debug and it seems to work correctly.   The modified function is below.

But now I'm running into an exception when trying to partition the rows.  I've spent a fair amount of time debugging the code, but I can't spot the issue.  Either my new function has a bug and isn't capturing all the data, or google isn't returning enough data to pass your partitioning logic.

Do you see anything wrong with the changes to the `execute_request` function that might cause the partitioning error?  And if not, is there a way to bypass the partitioning and assertion logic?  At this point, I mostly need the keyword data to join another dataset.  I don't need the data byPage/URL. 

For partitioning, I tried to set `check_aggregate` to always return True, but then I ran into Assertion errors, and the program seems to hang if I keep brute forcing with True. 

Cheers
Ryan  

```
    def execute_request(self, property_uri, request):
        """Executes a searchAnalytics.query request.

        Args:
        service: The webmasters service to use when executing the query.
        property_uri: The site or app URI to request data for.
        request: The request to be executed.

        Returns:
        An array of response rows.
        """
        if 'rowLimit' in request or 'startRow' in request:
            raise Exception('rowLimit and startRow are managed by execute_request')
        
        max_results = 25000
        request['rowLimit'] = max_results
        response = dict()

        for i in range(50):
            
            paged_response = self.service.searchanalytics().query(
            siteUrl=property_uri, body=request).execute()           

            if ROWS in paged_response:
                # Adding startRow after determining response has rows
                if 'startRow' in request:
                    pass
                else:
                    request['startRow'] = 0

                results = len(paged_response.get(ROWS))

                if results < max_results and i == 0:
                    del request['rowLimit']
                    del request['startRow']

                    return paged_response
                
                elif i == 0:
                    response = paged_response

                elif results < max_results:
                    new_rows = paged_response.get(ROWS)              
                    response.get(ROWS).extend(new_rows)
                    break

                else:
                    new_rows = paged_response.get(ROWS)                
                    response.get(ROWS).extend(new_rows)

                
                request['startRow'] += max_results

            else:
                response = paged_response
                break

            # Crude API call throttle
            # Do not exceed 1200QPM : https://developers.google.com/webmaster-tools/search-console-api-original/v3/limits
            time.sleep(60.0 / 1200.0)

        del request['rowLimit']

        if 'startRow' in request:
            del request['startRow']        

        return response
```

**Comment by adamlatchem** [comment]
Hi Ryan,

Oh cool so google upped the limit for the results at some point again. Thanks for taking a look at updating it. My thoughts on your code - I'd change it to do as google suggests here[https://developers.google.com/webmaster-tools/v1/how-tos/all-your-data] i.e. don't stop at 50 pages. If you do want an overall pagination limit I would add it in and pass in as an argument from the command line if you need to prevent running out of some quota somewhere or limiting the memory use ... however presumably if you cut the data off at 50 it could indeed cause an issue though as I didn't even know they'd upped the limit I am afraid I can't provide any insight on what you are seeing.

On the bug you mention can you send the stack? I know there is a problem currently trying to infer results I have not got round to fixing - the path that causes it hits an exception I put in the code so is in some sense 'known' so I'd like to see if it is that. But if you are hitting your 50 limit then first I'd suggest making the change above so you can get all your data and then see what happens. Perhaps you can put a cache infront of the end point e.g. squid or something if you need to test it.

Cheers

Adam

**Comment by kartzke** [comment]
Aww, my mistake, the API can still only return 50,000 rows as a max.  So the data and assertion checks will still fail on bigger data sets.

When I was originally testing this, I was only running it on 2 days of data, both of which had less than 50K rows returned each day.  So it sounds like I hit the problem you mentioned.  I just reran it, here's the stack.


```
05/07/2022 22:49:21 - googleapiclient.discovery - DEBUG - URL being requested: POST https://searchconsole.googleapis.com/webmasters/v3/sites/sc-domain%3Aexample.com/searchAnalytics/query?alt=json
Traceback (most recent call last):
  File "/toolchest/searchanalytics/search_analytics.py", line 122, in <module>
    main(ARGUMENT_PARSER)
  File "/toolchest/searchanalytics/search_analytics.py", line 113, in main
    gsc_query_service.get_data(
  File "/toolchest/searchanalytics/gsc_query_service.py", line 766, in get_data
    breakdown_rows = client.query_breakdown(
  File "/toolchest/searchanalytics/gsc_query_service.py", line 224, in query_breakdown
    query_page_secondary_rows = infer_secondary_rows(query_aggregates,
  File "/toolchest/searchanalytics/gsc_query_service.py", line 565, in infer_secondary_rows
    new_prim, new_sec = partition_rows(aggregate, breakdown)
  File "/toolchest/searchanalytics/gsc_query_service.py", line 594, in partition_rows
    raise Exception('Unable to partition rows: ' + str(aggregate) + ' :: ' + str(details_list))
```

**Comment by kartzke** [comment]
Although it's strange that [the docs](https://developers.google.com/webmaster-tools/v1/how-tos/all-your-data) you pointed me to make it sound `startRow` can be set higher than 25K.  When I tested this over the weekend, the responses I got beyond the first 50K rows were empty, they only had the `responseAggregationType` value.

**Comment by adamlatchem** [comment]
Hi Ryan - do you mean it is still 25,000? I reread the docs myself and think that is what the rowlimit on [this](https://developers.google.com/webmaster-tools/v1/searchanalytics/query) page is suggesting.

What the other page we're looking at is saying is in the special case start_date == end_date it will return everything using the page of 25,000 idea. That is my interpretation of it anyway. You could maybe use google API testing tool to confirm this. This is interesting because I eventually had to download one day at a time anyway. With your modification it would mean I would now get the 'missing' data.

Looking at the stack you have indeed hit the edge of my inference algorithm. Because I did not know what cases were missing (google just removes data to anonymise it etc but it is not 100% clear to me what) I put in the exception when I could detect there was a problem between the aggregate counts over rows google returned vs the inferred rows that are inconsistent.

I think you could add your idea in the case start_date == end_date with an optional limit (the google example suggests an infinite loop is okay but I personally would allow the user to put a cap on it just incase - though with a warning saying not all data is capture and that may break the inference algorithm. The cap might be useful just for testing e.g. your change). I then think you could try again and see if you still hit the inference exception and if you do we determine the best way to capture the data and debug this final case.

**Comment by kartzke** [comment]
Not quite.  The rowlimit is always 25,000.  The `startRow` option lets a user paginate to query another 25000 rows.  But in my testing, when `startRow == 50000` for a particular date, the response returned has zero rows, it only contained this:  `{'responseAggregationType': 'byProperty'}`.  

To double check, I just tried the following request for a 7 day period where every day had exactly 50K rows returned, and every time `startRow == 50000`, the response contained no rows.  Important to point out that the `request` shows startDate and endDate both use `flags.start_date`.  I have a loop iterating through the dates... `while flags.start_date <= flags.end_date`.   But I also tried setting `"endDate": flags.end_date`.  Pagination worked beyond `"startRow": 25000`, but got the same result, exactly 350,000 records.

```
    request = {
        "startDate": flags.start_date,
        "endDate": flags.start_date,
        "dimensions": ["date", "device", "country", "query"],
        "rowLimit": 25000,
        "startRow": 0,
        "aggregationType": "byProperty"
    }
```

If I remove device and country, every response contained exactly 5000 rows.  Despite `rowLimit == 25000`.

```
    request = {
        "startDate": flags.start_date,
        "endDate": flags.start_date,
        "dimensions": ["date", "query"],
        "rowLimit": 25000,
        "startRow": 0,
        "aggregationType": "byProperty"
    }
```

I also tried adding back device or country one at a time, but now I get less than 50K total rows, so no chance for a page 3.  Based on this, I'm petty sure the max rows per day is 50K, no matter how you query it.  The pagination seems to only work beyond `startRow == 25000` if you are querying more than one day of data.

**Comment by kartzke** [comment]
It's possible to increase the sampling rate is to have multiple GSC properties for the same domain, one for each URL silo (if you're lucky enough to have URLs well structured).  Otherwise, SOL. 

RE: https://similar.ai/blog/closing-google-search-console-sampling-gap/

```
example.com/
example.com/category/
example.com/products/
example.com/brand/
```

**Comment by adamlatchem** [comment]
Based on the docs maybe you need a "type": "web" in the request? There is also a section that suggests you may not get all the data if google decide it would use too much compute on their side. This is one of those "its not clear to me what is happening" but perhaps one simply has to put it down to this. With respect to your dimension tests - I think the help explains that again something to do with the specific query in the case start_date == end_date and how the query is further interpreted.

I notice google deprecated "searchType" which is what the code is currently using, though there are new values which would need to be added to the list that is enumerated... so you may need to just change it if you are still using the comitted code.
